print """
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

n = [1, 2]

while n[len(n)-1] <= 4000000:

	n.append(n[len(n)-1] + n[len(n)-2])

print sum(n)